name = "anythingllm-cloudflare"
compatibility_date = "2023-11-22"
pages_build_output_dir = "frontend/dist"

[env.production]
name = "anythingllm-cloudflare"
route = { pattern = "anythingllm.yourdomain.com", zone_name = "yourdomain.com" }

[env.production.vars]
ENVIRONMENT = "production"
API_BASE_URL = "https://anythingllm.yourdomain.com/api"

[env.development]
name = "anythingllm-cloudflare-dev"

[env.development.vars]
ENVIRONMENT = "development"
API_BASE_URL = "https://anythingllm-cloudflare-dev.pages.dev/api"

# Uncomment and configure if using Cloudflare D1 database
# [[env.production.d1_databases]]
# binding = "DB"
# database_name = "anythingllm-db"
# database_id = "your-database-id"

# [[env.development.d1_databases]]
# binding = "DB"
# database_name = "anythingllm-db-dev"
# database_id = "your-dev-database-id"

# Uncomment and configure if using Cloudflare KV for session storage
# [[env.production.kv_namespaces]]
# binding = "SESSIONS"
# id = "your-kv-namespace-id"

# [[env.development.kv_namespaces]]
# binding = "SESSIONS"
# id = "your-dev-kv-namespace-id"

# Uncomment and configure if using Cloudflare R2 for file storage
# [[env.production.r2_buckets]]
# binding = "DOCUMENTS"
# bucket_name = "anythingllm-documents"

# [[env.development.r2_buckets]]
# binding = "DOCUMENTS"
# bucket_name = "anythingllm-documents-dev"